### ISSUE TITLE
[Code Review] Use of routes

### ISSUE THREAD

**Issue by caneruguz** [cos-labs/share-analytics#132]
There are a couple of clean up updates that need to be done. Here are some ideas:

- The app currently is empty on root index and needs a /dashboard/institution to run properly. I may not be remembering the previous conversions on this decision but if it is possible to place it at the root level by removing /dashboard it may be better. 
https://github.com/cos-labs/share-analytics/blob/master/app/router.js#L10

- It looks like the /info route is not being used. The about information for institution is a widget in its own dashboard and its template is empty. 
https://github.com/cos-labs/share-analytics/blob/develop/app/router.js#L13

- ```Subject``` and ```user``` controllers don't have associated routes defined and they are cause errors. Is the intention to remove them?

**Comment by samanehsan** [comment]
These issues have been fixed!
