### ISSUE TITLE
[Code Review] Finish converting components to pod structure

### ISSUE THREAD

**Issue by caneruguz** [cos-labs/share-analytics#133]
Some components still have the non-pod structure. We should either remove them if not needed otherwise convert to pod structure. 

https://github.com/cos-labs/share-analytics/tree/master/app/templates/components

**Comment by samanehsan** [comment]
Those components are not being used anywhere and are deleted in https://github.com/cos-labs/share-analytics/pull/136 and https://github.com/cos-labs/share-analytics/pull/137
